In [20]:
import torch
from torch import nn, optim

class MyNet(nn.Module):
    def __init__(self):
        super(MyNet, self).__init__()
        self.conv1 = nn.Conv2d(1, 1, 3, stride=1, padding=1)
        self.conv2 = nn.Conv2d(1, 1, 3, stride=1, padding=1)
    
    def forward(self, x):
        x = self.conv1(x)
#         x = nn.functional.interpolate(x, scale_factor=2, mode='bilinear', align_corners=True)
        x = nn.functional.relu(x)
        x = self.conv2(x)
        return x
    
model = MyNet()
optimizer = optim.SGD(model.parameters(), lr=0.1)
    
x = torch.randn((1,1,4,4))
y = torch.ones((1,1,4,4))
mse_loss = nn.MSELoss()

print('Shape befort model:', x.shape)
output = model(x)
print('Shape after model:', output.shape)

optimizer.zero_grad()
loss = mse_loss(output, y)
loss.backward()
optimizer.step()

print('-'*30)
for it in model.parameters():
    print(it.shape)
    print(it.grad)
    print('-'*30)


Shape befort model: torch.Size([1, 1, 4, 4])
Shape after model: torch.Size([1, 1, 4, 4])
------------------------------
torch.Size([1, 1, 3, 3])
tensor([[[[ 0.0897, -0.0081, -0.0439],
          [-0.1440, -0.0855, -0.0509],
          [-0.1515, -0.1220,  0.0123]]]])
------------------------------
torch.Size([1])
tensor([0.3197])
------------------------------
torch.Size([1, 1, 3, 3])
tensor([[[[-0.0252, -0.0365, -0.0348],
          [-0.0541, -0.0637, -0.0575],
          [-0.0463, -0.0548, -0.0470]]]])
------------------------------
torch.Size([1])
tensor([-1.4214])
------------------------------
